def my_func(name):
    print('hello',name)
my_func('anwar')
#my_func()
def my_func2():
    print('hello')
#my_func2('anwar')
#both the comment lines throw the errors4